/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modeloLogin.Usuarios;

/**
 *
 * @author Oscar Andres Arce
 */
public class GestionEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form GestionEmpleados
     */
    
    private int mod;
    private int idUsuario;
    
    public GestionEmpleados() {
        initComponents();
        setLocationRelativeTo(null);

    }
    
    public GestionEmpleados(int mod, int usuarios){
        initComponents();
        setLocationRelativeTo(null);
        this.mod = mod;
        this.idUsuario = usuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnGenCont = new javax.swing.JButton();
        btnBajEmp = new javax.swing.JButton();
        btnAltaEmp1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion de Empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnRegresar.setText("Atras");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        btnGenCont.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnGenCont.setForeground(new java.awt.Color(255, 255, 255));
        btnGenCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono_Cont.png"))); // NOI18N
        btnGenCont.setText("Generar Contrato");
        btnGenCont.setBorderPainted(false);
        btnGenCont.setContentAreaFilled(false);
        btnGenCont.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenCont.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenCont.setIconTextGap(-3);
        btnGenCont.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGenCont.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGenCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenContActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 200, 140));

        btnBajEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnBajEmp.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnBajEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnBajEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono_UsrBaja.png"))); // NOI18N
        btnBajEmp.setText("Baja Empleado");
        btnBajEmp.setBorderPainted(false);
        btnBajEmp.setContentAreaFilled(false);
        btnBajEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBajEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBajEmp.setIconTextGap(-3);
        btnBajEmp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBajEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBajEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajEmpActionPerformed(evt);
            }
        });
        getContentPane().add(btnBajEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, 140));

        btnAltaEmp1.setBackground(new java.awt.Color(255, 255, 255));
        btnAltaEmp1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnAltaEmp1.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaEmp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono_Usr.png"))); // NOI18N
        btnAltaEmp1.setText("Alta Empleado");
        btnAltaEmp1.setBorderPainted(false);
        btnAltaEmp1.setContentAreaFilled(false);
        btnAltaEmp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltaEmp1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAltaEmp1.setIconTextGap(-3);
        btnAltaEmp1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAltaEmp1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAltaEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaEmp1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltaEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 140));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoMarron.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        GestionDeSistema ventana;
        try {
            ventana = new GestionDeSistema(mod, idUsuario);
            ventana.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(GestionEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAltaEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaEmp1ActionPerformed
        // TODO add your handling code here:
        AltaEmpleado ventana=new AltaEmpleado(mod, idUsuario);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAltaEmp1ActionPerformed

    private void btnGenContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenContActionPerformed
        // TODO add your handling code here:
        GenerarContrato ventana= new GenerarContrato(mod, idUsuario);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenContActionPerformed

    private void btnBajEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajEmpActionPerformed
        bajaEmpleado ventana = new bajaEmpleado(mod, idUsuario);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBajEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaEmp1;
    private javax.swing.JButton btnBajEmp;
    private javax.swing.JButton btnGenCont;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
